head.load(
    { file: "bower_components/angular/angular.js" },
    { file: "bower_components/angular-route/angular-route.js" },
    { file: "bower_components/angular-animate/angular-animate.js" },
    //{ file: "bower_components/angular-bootstrap/ui-bootstrap.js" },
    { file: "bower_components/jquery/jquery.js" },
    { file: "bower_components/bootstrap/dist/js/bootstrap.js" },
    { file: "bower_components/flat-ui/dist/js/flat-ui.min.js" },
    { file: "src/main/common/Common.js" },
    { file: "src/main/common/models/Event.js" },
    { file: "src/main/common/models/Attendee.js" },
    { file: "src/main/common/models/Prize.js" },
    { file: "src/main/common/models/Giveaway.js" },
    { file: "src/main/navigation/Navigation.js" },
    { file: "src/main/navigation/controllers/NavigationCtrl.js" },
    { file: "src/main/dashboard/Dashboard.js" },
    { file: "src/main/dashboard/controllers/DashboardCtrl.js" },
    { file: "src/main/event/Event.js" },
    { file: "src/main/event/controllers/EventCtrl.js" },
    { file: "src/main/prize/Prize.js" },
    { file: "src/main/prize/controllers/PrizeCtrl.js" },
    { file: "src/main/xenia.js" }
);